server:
  port: 3001
  origin: 'http://localhost:3000'

db:
  host: 'host.docker.internal'
  type: 'mysql'
  port: 3306
  username: 'root'
  password: ''
  database: 'template'
  synchronize: true

cookies:
  domain: 'localhost'
  secure: false

jwt:
  secret: 'secretkey123'